apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: replace-me
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: jenkins-ci-storage-class
  resources:
    requests:
      storage: 5Gi