apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: replace-me
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2